phpunit_target: tests/src

pr_matrix:
  drupal_core: ['10.6.x', '11.3.x']
  php_version: ['8.2', '8.3', '8.4']
  mariadb_version: ['10.6']
  exclude:
    - drupal_core: '10.6.x'
      php_version: '8.4'
    - drupal_core: '11.3.x'
      php_version: '8.2'

full_matrix:
  drupal_core: ['10.5.x', '10.6.x', '11.2.x', '11.3.x']
  php_version: ['8.2', '8.3', '8.4']
  mariadb_version: ['10.4', '10.6']
  exclude:
    - drupal_core: '10.5.x'
      php_version: '8.4'
    - drupal_core: '10.6.x'
      php_version: '8.4'
    - drupal_core: '11.2.x'
      php_version: '8.2'
    - drupal_core: '11.2.x'
      mariadb_version: '10.4'
    - drupal_core: '11.3.x'
      php_version: '8.2'
    - drupal_core: '11.3.x'
      mariadb_version: '10.4'
